version: 2
jobs:
  plan:
    docker:
      - image: python:3.8-alpine
    steps:
      - checkout
      - run: pip install awscli
      - run: aws s3 sync . $S3_URL --exclude="*.git*" --exclude="*img_src*"

workflows:
  version: 2
  build-test-and-approval-deploy:
    jobs:
      - plan  # your custom job from your config, that builds your code