version: 2
jobs:
  plan:
    docker:
      - image: python:3.8-alpine
    steps:
      - checkout
      - run: pip install awscli
      - run: which aws
      - run: aws --version
#   deploy:
#     docker:
#       - image: hashicorp/terraform:light
#     steps:
#       - checkout
#       - run: terraform init -backend-config=backend-config/staging
#       - run: terraform apply -auto-approve -var-file=staging.tfvars

workflows:
  version: 2
  build-test-and-approval-deploy:
    jobs:
      - plan  # your custom job from your config, that builds your code
    #   - hold: # <<< A job that will require manual approval in the CircleCI web application.
    #       type: approval # <<< This key-value pair will set your workflow to a status of "On Hold"
    #       requires: # We only run the "hold" job when test2 has succeeded
    #         - plan
    #   # On approval of the `hold` job, any successive job that requires the `hold` job will run. 
    #   # In this case, a user is manually triggering the deploy job.
    #   - deploy:
    #       requires:
    #         - hold
